label.titulo.pagina = TITULO DA PAGINA
label.novo = NOVO
label.excluir = EXCLUIR
label.editar = EDITAR
label.acao = A\u00C7\u00C3O
label.id = ID
label.nome = NOME
label.buscar.por = BUSCAR POR
label.escolha = ESCOLHA...
label.pesquisar = PESQUISAR
label.sim = SIM
label.nao = NAO
label.modal.titulo = CONFIRMA\u00C7\u00C3O DE EXCLUS\u00C3O
label.modal.corpo = DESEJA EXCLUIR ?
label.agendas= AGENDAS
label.agenda= AGENDA
label.periodo.disponivel= PER\u00cdODO DISPON\u00cdVEL
label.novo.agenda= NOVA AGENDA
label.editar.agenda= EDITAR AGENDA
label.titulo.pagina.consulta = CONSULTA
label.titulo.pagina.cadastro = CADASTRO
label.compromissos = COMPROMISSOS
label.compromisso = COMPROMISSO
label.novo.compromisso = NOVO COMPROMISSO
label.editar.compromisso = EDITAR COMPROMISSO
label.funcionario = FUNCION\u00C1RIO
label.data = DATA
label.horario = HOR\u00C1RIO
label.nenhum.registro = NENHUM REGISTRO ENCONTRADO